name: main_workflow
on:
  push:
    branches:
      - nodejs_jest_job
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_linter_job
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run jest test
      - run: npm install jest
      - run: npm test