name: main_workflow
on:
  push:
    branches:
      - nodejs_environment_job
env:
  DESTINATION_PERSON: 2DAW
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 10, 12 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setting node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_environment_job
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    needs: linter-execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: npm install jest
      - run: npm test
  environment_test_execution:
    runs-on: ubuntu-latest
    name: environment
    steps:
      - name: environment
        id: hello
        uses: adeloyedeji/github-actions-hello@v1.0
        with:
          who-to-greet: "$DESTINATION_PERSON JoaquimRS"