name: main_workflow
on:
  push:
    branches:
      - github_action_readme
env:
  DESTINATION_PERSON: 2DAW
jobs:
  test-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: npm install jest
      - run: npm test
        id: test
        continue-on-error: true
      - name: Failure
        if: steps.test.outcome != 'success'
        run: echo Error && exit 1